import type {
  AppState,
  CommitteeNotice,
  FormSnapshot,
  PolicyVersion,
  SubmissionFormData,
} from './models';
import { addMonths, addYears } from './utils';

const makeFormData = (overrides?: {
  form1?: Partial<SubmissionFormData['form1']>;
  form2?: Partial<SubmissionFormData['form2']>;
  form3?: Partial<SubmissionFormData['form3']>;
  form4?: Partial<SubmissionFormData['form4']>;
}): SubmissionFormData => {
  const base: SubmissionFormData = {
    form1: {
      inventionTitleKo: '경량 직조 벨트 강성 제어 구조',
      inventionTitleEn: 'Stiffness control structure for woven belt',
      desiredCountries: ['KR', 'US'],
      disclosureType: ['연구보고서'],
      inventionCategory: 'JOB_INVENTION',
      inventionStage: '③연구개발완료',
      additionalResearchNeeded: true,
      interestedCompanies: ['A사', 'B사'],
      researchNoteManaged: true,
      researchNoteLocation: '연구소 서버 / R&D 노트함',
      relatedPatentKeywords: 'belt, tension, woven structure',
    },
    form2: {
      assignmentShares: [
        { inventorName: '김발명', shareRatio: 70 },
        { inventorName: '정협업', shareRatio: 30 },
      ],
      assigneeName: '아시모리코리아(주)',
      assigneeTitle: '대표이사',
      assigneeCompany: '아시모리코리아(주)',
    },
    form3: {
      drawingDescription: '도 1은 직조 벨트의 장력 분산 구조를 나타낸다.',
      technicalField: '차량용 직조 벨트 장력 제어 기술',
      background: '종래 벨트는 장력 편차와 진동으로 품질 변동이 발생하였다.',
      technicalProblem:
        '장력 편차를 줄이면서 벨트 내구성을 확보할 필요가 있다.',
      solvingMeans: '보강사를 특정 패턴으로 재배열하고 가이드 롤러를 추가한다.',
      functionAndEffect: '장력 분산과 진동 억제를 동시에 달성한다.',
      examples: '파일럿 라인에서 20% 편차 감소를 확인하였다.',
      inventionEffect: '불량률 감소와 벨트 수명 향상',
      claims: ['청구항 1', '청구항 2', '청구항 3'],
    },
    form4: {
      priorPatentRows: [
        {
          existingPatent: 'KR 10-1234567 / 2021-01-11',
          noveltyDiff: '보강사 배열 위치가 다름',
          inventiveDiff: '장력 분산 알고리즘이 새로움',
        },
      ],
      referenceRows: [
        {
          reference: '섬유공학회지 2023, p.21-28',
          summary: '고강성 직조 패턴 연구',
          distinguishingFeature: '본 발명은 진동 억제 가이드 구조를 추가함',
        },
      ],
    },
  };

  return {
    form1: { ...base.form1, ...(overrides?.form1 ?? {}) },
    form2: { ...base.form2, ...(overrides?.form2 ?? {}) },
    form3: { ...base.form3, ...(overrides?.form3 ?? {}) },
    form4: { ...base.form4, ...(overrides?.form4 ?? {}) },
  };
};

const activePolicy: PolicyVersion = {
  id: 'policy-active',
  versionCode: 'AKS-A024-v1',
  name: '2026 직무발명 보상정책',
  status: 'ACTIVE',
  effectiveDate: '2026-04-01T00:00:00.000Z',
  noticeDate: '2026-03-15T00:00:00.000Z',
  createdBy: 'user-admin',
  approvedBy: 'user-admin',
  isDisadvantageous: false,
  changeSummary: '기본 운영 정책',
  grades: [
    { gradeCode: 'G1', gradeName: '1등급', minScore: 90, maxScore: 100 },
    { gradeCode: 'G2', gradeName: '2등급', minScore: 75, maxScore: 89.99 },
    { gradeCode: 'G3', gradeName: '3등급', minScore: 60, maxScore: 74.99 },
    { gradeCode: 'G4', gradeName: '4등급', minScore: 0, maxScore: 59.99 },
  ],
  criteria: [
    {
      criterionCode: 'TECHNICALITY',
      criterionName: '기술성',
      maxScore: 20,
      displayOrder: 1,
      levels: [
        { levelCode: 'LOW', levelName: '낮음', mappedScore: 5 },
        { levelCode: 'MID', levelName: '보통', mappedScore: 10 },
        { levelCode: 'HIGH', levelName: '높음', mappedScore: 15 },
        { levelCode: 'VERY_HIGH', levelName: '매우 높음', mappedScore: 20 },
      ],
    },
  ],
  cutoffRules: [
    { applicationScope: 'DOMESTIC', cutoffScore: 60 },
    { applicationScope: 'OVERSEAS', cutoffScore: 70 },
  ],
  rewardMatrix: [
    {
      id: 'matrix-1',
      rewardType: 'APPLICATION',
      rightType: 'PATENT',
      domesticOverseasType: 'DOMESTIC',
      gradeCode: 'G2',
      amount: 1800000,
    },
    {
      id: 'matrix-2',
      rewardType: 'REGISTRATION',
      rightType: 'PATENT',
      domesticOverseasType: 'DOMESTIC',
      gradeCode: 'G2',
      amount: 2300000,
    },
  ],
  formulaRules: [
    {
      id: 'formula-1',
      rewardType: 'PRACTICE',
      profitMin: 0,
      profitMax: 100000000,
      formulaType: 'VARIABLE',
      fixedAmount: 700000,
      numeratorSource: 'profit',
      denominatorValue: 10000,
      extraAmount: 0,
      roundingRule: 'ROUND',
    },
  ],
};

const committeeNotice: CommitteeNotice = {
  id: 'notice-1',
  submissionId: 'sub-3',
  templateCode: 'FORM5',
  documentNo: 'CNT-2026-0001',
  noticeDate: '2026-03-25T14:00:00.000Z',
  recipientUserId: 'user-inventor',
  title: '직무발명 심의결과 통지서',
  committeeChairName: '이심의',
  representativeName: '최관리',
  decisionItems: {
    jobInventionDecision: '직무발명',
    successionDecision: '회사 승계',
    patentGrade: 'G2',
    domesticOverseasPlan: '국내 출원',
    examinationRequestPlan: '심사청구 진행',
    remarks: '등록 보상 대상 예정',
  },
  generatedAt: '2026-03-25T14:00:00.000Z',
  generatedBy: 'user-manager',
  sentAt: '2026-03-25T14:10:00.000Z',
};

const formSnapshots: FormSnapshot[] = [
  {
    id: 'snapshot-1',
    formCode: 'FORM1',
    targetType: 'SUBMISSION',
    targetId: 'sub-1',
    title: '별지 제1호 발명신고서',
    generatedBy: 'user-inventor',
    generatedAt: '2026-04-01T09:05:00.000Z',
    fileName: 'FORM1-sub-1.pdf',
    filePath: 'tmp/generated-docs/FORM1-sub-1.pdf',
    previewLines: ['발명신고서', '발명의 명칭: 경량 직조 벨트 강성 제어 구조'],
  },
];

export const seedData: AppState = {
  users: [
    {
      id: 'user-inventor',
      employeeNo: '1001',
      name: '김발명',
      email: 'inventor@ashimori.example',
      department: '연구개발팀',
      positionName: '선임연구원',
      status: 'ACTIVE',
      roles: [{ code: 'INVENTOR', scopeType: 'SELF' }],
    },
    {
      id: 'user-inventor-2',
      employeeNo: '1002',
      name: '정협업',
      email: 'inventor2@ashimori.example',
      department: '신소재개발팀',
      positionName: '연구원',
      status: 'ACTIVE',
      roles: [{ code: 'INVENTOR', scopeType: 'SELF' }],
    },
    {
      id: 'user-manager',
      employeeNo: '2001',
      name: '박특허',
      email: 'ip@ashimori.example',
      department: '특허관리전담부서',
      positionName: '책임매니저',
      status: 'ACTIVE',
      roles: [{ code: 'IP_MANAGER', scopeType: 'ALL' }],
    },
    {
      id: 'user-committee',
      employeeNo: '3001',
      name: '이심의',
      email: 'committee@ashimori.example',
      department: '심의위원회',
      positionName: '위원장',
      status: 'ACTIVE',
      roles: [{ code: 'COMMITTEE', scopeType: 'ALL' }],
    },
    {
      id: 'user-admin',
      employeeNo: '9001',
      name: '최관리',
      email: 'admin@ashimori.example',
      department: '경영지원',
      positionName: '시스템관리자',
      status: 'ACTIVE',
      roles: [{ code: 'ADMIN', scopeType: 'ALL' }],
    },
  ],
  submissions: [
    {
      id: 'sub-1',
      submissionNo: 'SUB-2026-0001',
      title: '경량 직조 벨트 강성 제어 구조',
      submitterUserId: 'user-inventor',
      summary: '차량용 벨트 소재의 장력 편차를 줄이는 직조 구조 제안',
      businessUnit: '자동차부품BU',
      status: 'UNDER_REVIEW',
      submittedAt: '2026-04-01T09:00:00.000Z',
      createdAt: '2026-03-28T09:00:00.000Z',
      updatedAt: '2026-04-01T09:00:00.000Z',
      dueDate: addMonths('2026-04-01T09:00:00.000Z', 4),
      shares: [
        {
          id: 'share-1',
          userId: 'user-inventor',
          inventorName: '김발명',
          inventorNameEn: 'Kim Inventor',
          shareRatio: 70,
          isPrimary: true,
          department: '연구개발팀',
          phoneNumber: '010-1111-2222',
        },
        {
          id: 'share-2',
          userId: 'user-inventor-2',
          inventorName: '정협업',
          inventorNameEn: 'Jung Collaborator',
          shareRatio: 30,
          isPrimary: false,
          department: '신소재개발팀',
          phoneNumber: '010-2222-3333',
        },
      ],
      attachments: [],
      reviewNotes: [],
      snapshot: {
        title: '경량 직조 벨트 강성 제어 구조',
        summary: '차량용 벨트 소재의 장력 편차를 줄이는 직조 구조 제안',
        submittedAt: '2026-04-01T09:00:00.000Z',
        shares: [
          {
            id: 'share-1',
            userId: 'user-inventor',
            inventorName: '김발명',
            shareRatio: 70,
            isPrimary: true,
          },
          {
            id: 'share-2',
            userId: 'user-inventor-2',
            inventorName: '정협업',
            shareRatio: 30,
            isPrimary: false,
          },
        ],
      },
      formData: makeFormData(),
    },
    {
      id: 'sub-2',
      submissionNo: 'SUB-2026-0002',
      title: '내열 섬유 접합 공정 개선안',
      submitterUserId: 'user-inventor-2',
      summary: '접합 온도 편차를 줄이는 보강 공정 제안',
      businessUnit: '신소재BU',
      status: 'RETURNED',
      submittedAt: '2026-03-29T10:00:00.000Z',
      createdAt: '2026-03-26T10:00:00.000Z',
      updatedAt: '2026-04-02T11:00:00.000Z',
      dueDate: addMonths('2026-03-29T10:00:00.000Z', 4),
      shares: [
        {
          id: 'share-3',
          userId: 'user-inventor-2',
          inventorName: '정협업',
          shareRatio: 100,
          isPrimary: true,
          department: '신소재개발팀',
        },
      ],
      attachments: [],
      reviewNotes: [
        {
          id: 'note-1',
          type: 'REVIEW_REQUEST',
          reason: '양도증 서명 누락으로 보완이 필요합니다.',
          createdAt: '2026-04-02T11:00:00.000Z',
          createdBy: 'user-manager',
        },
      ],
      snapshot: {
        title: '내열 섬유 접합 공정 개선안',
        summary: '접합 온도 편차를 줄이는 보강 공정 제안',
        submittedAt: '2026-03-29T10:00:00.000Z',
        shares: [
          {
            id: 'share-3',
            userId: 'user-inventor-2',
            inventorName: '정협업',
            shareRatio: 100,
            isPrimary: true,
          },
        ],
      },
      formData: makeFormData({
        form1: {
          inventionTitleKo: '내열 섬유 접합 공정 개선안',
          desiredCountries: ['KR'],
        },
      }),
    },
    {
      id: 'sub-3',
      submissionNo: 'SUB-2026-0003',
      title: '저진동 장력 보정 롤러 구조',
      submitterUserId: 'user-inventor',
      summary: '회전 시 진동을 억제해 장력 편차를 줄이는 롤러 구조',
      businessUnit: '자동차부품BU',
      status: 'ACCEPTED',
      submittedAt: '2026-03-18T09:00:00.000Z',
      createdAt: '2026-03-14T09:00:00.000Z',
      updatedAt: '2026-03-25T13:30:00.000Z',
      dueDate: addMonths('2026-03-18T09:00:00.000Z', 4),
      shares: [
        {
          id: 'share-4',
          userId: 'user-inventor',
          inventorName: '김발명',
          shareRatio: 60,
          isPrimary: true,
        },
        {
          id: 'share-5',
          userId: 'user-inventor-2',
          inventorName: '정협업',
          shareRatio: 40,
          isPrimary: false,
        },
      ],
      attachments: [],
      reviewNotes: [],
      snapshot: {
        title: '저진동 장력 보정 롤러 구조',
        summary: '회전 시 진동을 억제해 장력 편차를 줄이는 롤러 구조',
        submittedAt: '2026-03-18T09:00:00.000Z',
        shares: [
          {
            id: 'share-4',
            userId: 'user-inventor',
            inventorName: '김발명',
            shareRatio: 60,
            isPrimary: true,
          },
          {
            id: 'share-5',
            userId: 'user-inventor-2',
            inventorName: '정협업',
            shareRatio: 40,
            isPrimary: false,
          },
        ],
      },
      formData: makeFormData({
        form1: {
          inventionTitleKo: '저진동 장력 보정 롤러 구조',
        },
      }),
    },
  ],
  successionDecisions: [
    {
      id: 'decision-1',
      submissionId: 'sub-3',
      decisionType: 'ACCEPT',
      decidedBy: 'user-manager',
      decidedAt: '2026-03-25T13:30:00.000Z',
      dueDate: addMonths('2026-03-18T09:00:00.000Z', 4),
      reason: '국내 출원 대상으로 승계 결정',
    },
  ],
  committeeNotices: [committeeNotice],
  appealRequests: [
    {
      id: 'appeal-1',
      submissionId: 'sub-3',
      requestType: 'REVIEW',
      applicantUserId: 'user-inventor',
      applicantName: '김발명',
      applicantDepartment: '연구개발팀',
      receivedAt: '2026-04-02T10:00:00.000Z',
      receivedNo: 'APL-2026-0001',
      inventionTitle: '저진동 장력 보정 롤러 구조',
      reasonOccurredAt: '2026-03-25T14:10:00.000Z',
      committeeNoticeDate: '2026-03-25T14:10:00.000Z',
      purpose: '등급 재검토 요청',
      reason: '시장성 평가가 실제 사업 가능성보다 낮게 반영되었다고 판단함',
      evidenceFiles: [],
      status: 'UNDER_REVIEW',
    },
  ],
  appealDecisions: [
    {
      id: 'appeal-decision-1',
      appealRequestId: 'appeal-1',
      templateCode: 'FORM8',
      documentNo: 'APL-DEC-2026-0001',
      decisionDate: '2026-04-05T10:00:00.000Z',
      requestSummary: '시장성 재검토 요청',
      decisionSummary: '기존 심의결과 유지',
      generatedBy: 'user-committee',
      notifiedAt: '2026-04-05T15:00:00.000Z',
    },
  ],
  applicationNotices: [
    {
      id: 'app-notice-1',
      patentId: 'pat-2',
      templateCode: 'FORM9',
      documentNo: 'PAT-NOTICE-2026-0001',
      recipientUserId: 'user-inventor',
      inventionTitle: '저진동 장력 보정 롤러 구조',
      inventorNames: ['김발명', '정협업'],
      rightContent: '특허권',
      isFiled: true,
      applicationDate: '2026-03-30T00:00:00.000Z',
      applicationNo: '10-2026-0000981',
      generatedAt: '2026-03-30T11:00:00.000Z',
      generatedBy: 'user-manager',
      sentAt: '2026-03-30T11:10:00.000Z',
    },
  ],
  formSnapshots,
  evaluations: [
    {
      id: 'eval-1',
      targetType: 'SUBMISSION',
      targetId: 'sub-1',
      policyVersionId: activePolicy.id,
      evaluationRound: 1,
      status: 'DRAFT',
      totalScore: 72,
      gradeCode: 'G3',
      evaluatorUserId: 'user-committee',
      createdAt: '2026-04-02T02:00:00.000Z',
      updatedAt: '2026-04-02T02:00:00.000Z',
      items: [
        {
          criterionCode: 'TECHNICALITY',
          selectedLevelCode: 'HIGH',
          selectedScore: 15,
        },
      ],
    },
  ],
  meetingMinutes: [
    {
      id: 'meeting-1',
      title: '4월 1차 직무발명 심의위원회',
      meetingDate: '2026-04-03T01:00:00.000Z',
      status: 'DRAFT',
      retentionUntil: addYears('2026-04-03T01:00:00.000Z', 3),
      attendees: ['이심의', '박특허'],
      agenda: ['SUB-2026-0001 등급 검토'],
      resolution: '추가 검토 후 확정 예정',
    },
  ],
  patents: [
    {
      id: 'pat-1',
      submissionId: 'sub-1',
      title: '경량 직조 벨트 강성 제어 구조',
      rightType: 'PATENT',
      countryCode: 'KR',
      applicationNo: '10-2026-0001234',
      applicationDate: '2026-04-10T00:00:00.000Z',
      currentStatus: 'OA',
      ownerType: 'COMPANY',
      managerUserId: 'user-manager',
      documents: [],
      oaEvents: [
        {
          id: 'oa-1',
          oaNo: 'OA-2026-01',
          dueDate: addMonths('2026-05-01T00:00:00.000Z', 1),
          status: 'PREPARING',
          assigneeUserId: 'user-manager',
          documents: [],
        },
      ],
      statusHistory: [
        {
          toStatus: 'FILED',
          reason: '회사 명의 출원 완료',
          changedBy: 'user-manager',
          changedAt: '2026-04-10T09:00:00.000Z',
        },
        {
          fromStatus: 'FILED',
          toStatus: 'OA',
          reason: '중간사건 수신',
          changedBy: 'user-manager',
          changedAt: '2026-05-01T09:00:00.000Z',
        },
      ],
    },
    {
      id: 'pat-2',
      submissionId: 'sub-3',
      title: '저진동 장력 보정 롤러 구조',
      rightType: 'PATENT',
      countryCode: 'KR',
      applicationNo: '10-2026-0000981',
      applicationDate: '2026-03-30T00:00:00.000Z',
      registrationNo: '10-2550001',
      registrationDate: '2026-04-28T00:00:00.000Z',
      currentStatus: 'REGISTERED',
      ownerType: 'COMPANY',
      managerUserId: 'user-manager',
      documents: [],
      oaEvents: [],
      statusHistory: [
        {
          toStatus: 'FILED',
          reason: '국내 출원 완료',
          changedBy: 'user-manager',
          changedAt: '2026-03-30T09:00:00.000Z',
        },
        {
          fromStatus: 'FILED',
          toStatus: 'REGISTERED',
          reason: '등록 완료',
          changedBy: 'user-manager',
          changedAt: '2026-04-28T11:00:00.000Z',
        },
      ],
    },
  ],
  rewards: [],
  policies: [activePolicy],
  announcements: [],
  consents: [],
  notifications: [
    {
      id: 'noti-1',
      userId: 'user-manager',
      type: 'SUBMISSION_DUE',
      channel: 'IN_APP',
      title: '승계 결정 기한 임박',
      body: 'SUB-2026-0001 신고 건의 4개월 기한을 추적 중입니다.',
      status: 'SENT',
      sentAt: '2026-04-02T01:00:00.000Z',
    },
  ],
  auditLogs: [],
};
