export const bootstrapPolicy = {
  versionCode: 'AKS-A024-v1',
  name: 'AKS-A024 Active Policy',
  status: 'ACTIVE',
  effectiveDate: new Date('2026-04-01T00:00:00.000Z'),
  noticeDate: new Date('2026-03-15T00:00:00.000Z'),
  createdBy: 'user-admin',
  approvedBy: 'user-admin',
  isDisadvantageous: false,
  changeSummary: 'Initial active policy for submission evaluation',
  grades: [
    {
      gradeCode: 'G1',
      gradeName: '1등급',
      minScore: 90,
      maxScore: 100,
      displayOrder: 1,
    },
    {
      gradeCode: 'G2',
      gradeName: '2등급',
      minScore: 75,
      maxScore: 89.99,
      displayOrder: 2,
    },
    {
      gradeCode: 'G3',
      gradeName: '3등급',
      minScore: 60,
      maxScore: 74.99,
      displayOrder: 3,
    },
    {
      gradeCode: 'G4',
      gradeName: '4등급',
      minScore: 0,
      maxScore: 59.99,
      displayOrder: 4,
    },
  ],
  criteria: [
    {
      criterionCode: 'TECHNICALITY',
      criterionName: '기술성',
      maxScore: 20,
      displayOrder: 1,
      levels: [
        {
          levelCode: 'LOW',
          levelName: '낮음',
          mappedScore: 5,
          displayOrder: 1,
        },
        {
          levelCode: 'MID',
          levelName: '보통',
          mappedScore: 10,
          displayOrder: 2,
        },
        {
          levelCode: 'HIGH',
          levelName: '높음',
          mappedScore: 15,
          displayOrder: 3,
        },
        {
          levelCode: 'VERY_HIGH',
          levelName: '매우 높음',
          mappedScore: 20,
          displayOrder: 4,
        },
      ],
    },
    {
      criterionCode: 'PRACTICABILITY',
      criterionName: '실시가능성',
      maxScore: 20,
      displayOrder: 2,
      levels: [
        {
          levelCode: 'LOW',
          levelName: '낮음',
          mappedScore: 5,
          displayOrder: 1,
        },
        {
          levelCode: 'PARTIAL',
          levelName: '보완 후 가능',
          mappedScore: 10,
          displayOrder: 2,
        },
        {
          levelCode: 'HIGH',
          levelName: '높음',
          mappedScore: 15,
          displayOrder: 3,
        },
        {
          levelCode: 'VERY_HIGH',
          levelName: '즉시 실시가능',
          mappedScore: 20,
          displayOrder: 4,
        },
      ],
    },
    {
      criterionCode: 'ORIGINALITY',
      criterionName: '독창성',
      maxScore: 20,
      displayOrder: 3,
      levels: [
        {
          levelCode: 'LOW',
          levelName: '낮음',
          mappedScore: 5,
          displayOrder: 1,
        },
        {
          levelCode: 'MID',
          levelName: '보통',
          mappedScore: 10,
          displayOrder: 2,
        },
        {
          levelCode: 'HIGH',
          levelName: '높음',
          mappedScore: 15,
          displayOrder: 3,
        },
        {
          levelCode: 'VERY_HIGH',
          levelName: '매우 높음',
          mappedScore: 20,
          displayOrder: 4,
        },
      ],
    },
    {
      criterionCode: 'ECONOMIC_VALUE',
      criterionName: '경제적 가치',
      maxScore: 20,
      displayOrder: 4,
      levels: [
        {
          levelCode: 'LOW',
          levelName: '낮음',
          mappedScore: 5,
          displayOrder: 1,
        },
        {
          levelCode: 'MID',
          levelName: '보통',
          mappedScore: 10,
          displayOrder: 2,
        },
        {
          levelCode: 'HIGH',
          levelName: '높음',
          mappedScore: 15,
          displayOrder: 3,
        },
        {
          levelCode: 'VERY_HIGH',
          levelName: '매우 높음',
          mappedScore: 20,
          displayOrder: 4,
        },
      ],
    },
    {
      criterionCode: 'EXCLUSIVITY',
      criterionName: '독점성',
      maxScore: 10,
      displayOrder: 5,
      levels: [
        {
          levelCode: 'LOW',
          levelName: '낮음',
          mappedScore: 3,
          displayOrder: 1,
        },
        {
          levelCode: 'MID',
          levelName: '보통',
          mappedScore: 6,
          displayOrder: 2,
        },
        {
          levelCode: 'HIGH',
          levelName: '높음',
          mappedScore: 10,
          displayOrder: 3,
        },
      ],
    },
    {
      criterionCode: 'LIFESPAN',
      criterionName: '기술 수명',
      maxScore: 10,
      displayOrder: 6,
      levels: [
        {
          levelCode: 'SHORT',
          levelName: '1년 미만',
          mappedScore: 3,
          displayOrder: 1,
        },
        {
          levelCode: 'MID',
          levelName: '5년 미만',
          mappedScore: 6,
          displayOrder: 2,
        },
        {
          levelCode: 'LONG',
          levelName: '10년 미만',
          mappedScore: 8,
          displayOrder: 3,
        },
        {
          levelCode: 'VERY_LONG',
          levelName: '10년 이상',
          mappedScore: 10,
          displayOrder: 4,
        },
      ],
    },
  ],
} as const;
